@HOST = http://localhost:5000/api/v1

### 
POST {{HOST}}/users
Content-Type: application/json

{
  "name": "Daniel Santos",
  "email": "daniel@email.com",
  "password": "123123"
}

###
GET {{HOST}}/users

### 
GET {{HOST}}/users/2

### 
PUT {{HOST}}/users/3
Content-Type: application/json

{
  "name": "João",
  "email": "joao@gmail.com",
  "password": "123123"
}


###
DELETE {{HOST}}/users/3

### PRODUCTS
GET {{HOST}}/products

###
POST {{HOST}}/products
Content-Type: application/json

{
  "title": "Cafeteira Industrial",
  "slug": "cafeteira-industrial",
  "price": 100,
  "description": "Faça um café maravilhoso",
  "categoryId": 4,
  "brandId": 1
}