services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookstore
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=bookstore
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:4000/api
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
