@HOST = http://localhost:8080/api/v1

GET {{HOST}}/users
###
GET {{HOST}}/users/0199935a-03ec-7059-b32d-820402b4dc4d
###
DELETE {{HOST}}/users/01999359-3596-7428-9198-74ae6e7c5afa

###
PUT {{HOST}}/users/0199935a-0b08-77de-ab55-0e1e8c3008a9
Content-Type: application/json

{
  "name": "Daniel Santos",
  "email": "daniel@email.com",
  "password": "123123"
}

###
POST {{HOST}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@email.com",
  "password": "1231fgasd"
}

###
POST {{HOST}}/users
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@email.com",
  "password": "123123"
}

### ------ SIGN-UP ------ ###
POST {{HOST}}/auth/sign-up
Content-Type: application/json

{
  "name": "Pedro",
  "email": "pedro@email.com",
  "password": "123123"
}
###
POST {{HOST}}/auth/sign-up
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@email.com",
  "password": "123123"
}


### ------ SIGN-IN ------ ###
POST {{HOST}}/auth/sign-in
Content-Type: application/json

{
  "email": "john@email.com",
  "password": "123123"
}

