@HOST = http://localhost:5000/api/v1

GET {{HOST}}/users

###
POST {{HOST}}/users
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@email.com",
  "password": "aslçdfnaweio"
}

###
POST {{HOST}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@email.com",
  "password": "1231fgasd"
}