@HOST = http://localhost:8080/api/v1

GET {{HOST}}/users
###
GET {{HOST}}/users/0199ac11-baec-716c-8465-5b6437e6a52c
###
DELETE {{HOST}}/users/0199bef7-865a-73ed-8875-53345377c3c3

### ------ UPDATE ----- ###
PUT {{HOST}}/users/0199c01f-7ec2-743f-921a-bded881b776e
Content-Type: application/json

{
  "name": "Daniel da Silva Santos",
  "email": "daniel@email.com",
  "password": "321321"
}

### ----- CREATE ----- ###
POST {{HOST}}/users
Content-Type: application/json

{
  "name": "Dan Doe",
  "email": "dan@email.com",
  "password": "1231fgasd"
}

###
POST {{HOST}}/users
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@email.com",
  "password": "123123"
}

### ------ SIGN-UP ------ ###
POST {{HOST}}/auth/sign-up
Content-Type: application/json

{
  "name": "Pedro",
  "email": "pedro@email.com",
  "password": "123123"
}
###
POST {{HOST}}/auth/sign-up
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@email.com",
  "password": "123123"
}

### ------ AUTH ------ ###
POST {{HOST}}/auth/sign-in
Content-Type: application/json

{
  "email": "john@email.com"
}

###
POST {{HOST}}/auth/sign-out

### ------- SESSIONS ------- ###
GET {{HOST}}/sessions

###
POST {{HOST}}/sessions
Content-Type: application/json

{

}