services:
  backend-dev:
    build:
      context: .
      target: dev
    image: bookstore:dev
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - node-modules:/app/node_modules

  backend-prod:
    build:
      context: .
      target: prod
    image: bookstore:prod
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  node-modules:
